# fly.toml app configuration file generated for zstrike-google-mcp on 2026-04-09T12:49:56+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zstrike-google-mcp'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
